name: aac_provider_lints
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  analyzer:
  analyzer_plugin:
  custom_lint_builder:
  riverpod_analyzer_utils:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

